---
# Installs and configures the Rspamd spam filtering system.

- name: Ensure repository key for Rspamd is in place
  apt_key: url=https://rspamd.com/apt-stable/gpg.key state=present
  tags:
    - dependencies

- name: Add Rspamd repository
  apt_repository: repo="deb https://rspamd.com/apt-stable/ {{ ansible_distribution_release }} main"
  tags:
    - dependencies

- name: Install Rspamd and Redis
  apt: pkg={{ item }} state=installed update_cache=yes
  with_items:
    - rspamd
    - redis-server
  tags:
    - dependencies

# - name: Set Redis Maxmemory
- name: Set Redis Maxmemory
  lineinfile:
    dest=/etc/redis/redis.conf
    regexp="^# maxmemory"
    line=" maxmemory 500mb"
    state=present

# - name: Set Redis memory-policy
- name: Set Redis memory-policy
  lineinfile:
    dest=/etc/redis/redis.conf
    regexp="^# maxmemory-policy"
    line=" maxmemory-policy volatile-lru"
    state=present

- name: Bind rspamd to localhost
  copy:
    src: rspamd_local_worker_normal.inc
    dest: /etc/rspamd/local.d/worker-normal.inc
    owner: root
    group: root
    mode: 0644
  notify: restart rspamd

- name: Set rspamd proxy mode
  copy:
    src: rspamd_local_worker_proxy.inc
    dest: /etc/rspamd/local.d/worker-proxy.inc
    owner: root
    group: root
    mode: 0644
  notify: restart rspamd

- name: Set rspamd to use Redis classifier
  copy:
    src: rspamd_local_classifier_bayes.conf
    dest: /etc/rspamd/local.d/classifier-bayes.conf
    owner: root
    group: root
    mode: 0644
  notify: restart rspamd

# disable worker-normal


- name: Start redis
  service: name=redis-server state=started

- name: Start rspamd systemd listener
  service: name=rspamd state=started
